### ISSUE TITLE
reeeeeee

### ISSUE THREAD

**Issue by Gremious** [Gremious/StS-TheThiefMod#21]
![image](https://user-images.githubusercontent.com/21365711/51946460-7f4c4d00-2419-11e9-958d-79f30067bc4c.png)

**Comment by Gremious** [comment]
![image](https://user-images.githubusercontent.com/21365711/51946470-87a48800-2419-11e9-869b-0f2fa951a884.png)

**Comment by taviato** [comment]
you should be ethereally shamed about all your bugs
gottem

**Comment by Gremious** [comment]
🤔
