### ISSUE TITLE
Create JAR file?

### ISSUE THREAD

**Issue by AvangionQ** [Gremious/StS-TheThiefMod#89]
Is there a version of this available for Mod the Spire 3.6.3? I want to try it out ...

**Comment by Gremious** [comment]
This mod is curretnly very much still in-progress. I'll be releasing this properly on the workshop once it's fully done, outside of some personal friends for playtesting. Expect it around summer time, as I have all of the art to draw still, and it's exam season. Sorry, it's a bit too early for the thief yet! =)


As for MTS 3.6.3? No. Buy the game or use a friend's Steam library.
